### ISSUE TITLE
Mushroom blocks will cause single blocks to disappear directly!

### ISSUE THREAD

**Issue by wlm1455925277** [BG-Software-LLC/SSB-OneBlock#76] opened 2024-02-12 12:58 UTC
### Minecraft's Version

Current: git-SlimeWorldManager-25 (MC: 1.20.4)*
* Unknown version

### Plugin's Version

SuperiorSkyblock2 version 2023.3-b138
Feature packed Skyblock core.
Website: https://bg-software.com/
Author: Ome_R

### Describe the bug

Mushroom blocks will cause single blocks to disappear directly!

### To Reproduce

At the time of printing in this country, the meeting was directly disappeared!

### Additional Information

Mushroom blocks will cause single blocks to disappear directly!

**Comment by OmerBenGera** [comment] 2024-02-16 15:23
I don't understand what the issue is
Please give me more details, or a configuration file of the plugin that doesn't work

**Comment by wlm1455925277** [comment] 2024-02-16 15:29
> 我不明白问题是什么 请给我更多详细信息，或者该插件的配置文件不起作用

My configuration belongs to a paid purchase configuration and I cannot send it here. Can you let me contact you on Discord?

**Comment by wlm1455925277** [comment] 2024-02-16 15:31
> 我不明白问题是什么 请给我更多详细信息，或者该插件的配置文件失效

My name is wlm123. I just posted a 1 on your channel

**Comment by OmerBenGera** [comment] 2024-02-16 16:24
> > 我不明白问题是什么 请给我更多详细信息，或者该插件的配置文件不起作用
> 
> My configuration belongs to a paid purchase configuration and I cannot send it here. Can you let me contact you on Discord?

then contact them for help.
If their configuration does not work, they should fix it.

**Comment by wlm1455925277** [comment] 2024-02-16 17:26
> > > 我不明白问题是什么，请给我更多详细信息，或者该插件的配置文件失效
> > 
> > 
> > 我的配置属于付费购买配置，无法发送到这里。你能让我在 Discord 上联系你吗？
> 
> 然后联系他们寻求帮助。 如果他们的配置不起作用，他们应该修复它。

When brushing single blocks, there is a chance that the mushroom blocks will disappear directly after being knocked out, and this problem also occurs in your original configuration!

**Comment by wlm1455925277** [comment] 2024-02-16 17:38
https://github.com/BG-Software-LLC/SSB-OneBlock/assets/87473483/63e764ca-76b7-42a9-817e-f0c02bf1fb78

**Comment by wlm1455925277** [comment] 2024-02-16 17:41
> > > 我不明白问题是什么，请给我更多详细信息，或者该插件的配置文件失效
> > 
> > 
> > 我的配置属于付费购买配置，无法发送到这里。你能让我在 Discord 上联系你吗？
> 
> 然后联系他们寻求帮助。 如果他们的配置不起作用，他们应该修复它。

The single block in the video disappeared after being knocked out due to the generation of mushroom blocks, and I replaced it with a non mushroom block block to restore it to normal!

**Comment by wlm1455925277** [comment] 2024-02-16 17:49
And the single block will disappear due to explosion!

**Comment by OmerBenGera** [comment] 2024-02-17 09:35
Try it on a server with only SSB installed & one block module installed, let me know if it still occurs.

**Comment by wlm1455925277** [comment] 2024-02-17 13:20
> 在只安装了SSB和一个块模块的服务器上尝试一下，如果它仍然发生，请告诉我。

That problem only occurs when he uses it with ItemsAdder!

**Comment by OmerBenGera** [comment] 2024-03-15 10:21
Makes more sense now
I created a ticket for you on Discord - please send me a copy of your Oneblock configuration files in there.

**Comment by OmerBenGera** [comment] 2024-12-21 13:12
I am closing this for now
If the issue still occurs, let me know

**Closed by OmerBenGera** 2024-12-21 13:12 UTC
Labels: 📝 Missing information
