### ISSUE TITLE
Oneblock phases

### ISSUE THREAD

**Issue by xOpasik** [BG-Software-LLC/SSB-OneBlock#27] opened 2022-06-08 10:35 UTC
### Minecraft's Version

1.17.1 

### Plugin's Version

newest

### Describe the bug

Earlier I reported that there was a problem with generator phases resetting after server restart. Generally, an unusual situation, their progress was reset, etc., they normally had to extract resources from phase 1, but some people have a higher level of the generator phase shown on the scoreboard than they currently have

### To Reproduce

In fact, this error occurs only in people who still had the same island, if you delete it and recreate it correctly, everything is fine

### Additional Information

![image](https://user-images.githubusercontent.com/105610066/172596120-64937d22-184e-417b-b21c-70a8894b219f.png)

              - ' &#7CFC5A•&#C7C7C7 Poziom generatora: &#F8BE00%superior_oneblock_phase_level%'
              - ' &#7CFC5A•&#C7C7C7 Postęp: &#2AD5EF%superior_oneblock_progress%%'
              - '   &7[&r%progress_bar_{superior_oneblock_progress}_c:&#2AD5EF■_p:&#2AD5EF■_r:&7■_l:10_m:100_fullbar:&#00E10BOsiągnąłeś lvl UP!%&7]'

**Comment by OmerBenGera** [comment] 2022-06-08 13:49
Duplicate of #23 
There is no need to open new bug reports for the same reported issue.
Include the new information in the other report that you already created before.

**Closed by OmerBenGera** 2022-06-08 13:49 UTC
Labels: Pending
