### ISSUE TITLE
Oneblock generator

### ISSUE THREAD

**Issue by xOpasik** [BG-Software-LLC/SSB-OneBlock#29] opened 2022-06-14 06:12 UTC
### Minecraft's Version

1.17.1

### Plugin's Version

newest

### Describe the bug

The island levels are subtracted while extracting resources from the oneblock generator
![image](https://user-images.githubusercontent.com/105610066/173505763-4163caa7-62bc-4d65-a77d-c4daaf209d72.png)

### To Reproduce

Keep extracting blocks from oneblock

### Additional Information

In fact, I guess that it works on the basis that when a block appears "it does not give the island level" but if it breaks down and does not put it back, it takes the island level and it is a vicious circle

**Comment by OmerBenGera** [comment] 2022-06-14 08:43
When the generator generates blocks, the values increase. When you break the block, they are decreased.

**Comment by OmerBenGera** [comment] 2022-06-14 08:43
When the generator generates blocks, the values increase. When you break the block, they are decreased.

**Comment by xOpasik** [comment] 2022-06-14 18:13
No, they're still negative. Please check it. The principle is that if a block appears, it doesn't add value, you destroy it, it takes the level. You'd have to put it back on

**Comment by OmerBenGera** [comment] 2022-06-14 21:18
The issue happens because the module fires the BlockBreakEvent as well as calling handleBlockBreak. 
Thanks for reporting, will be fixed.

**Comment by xOpasik** [comment] 2022-06-15 10:08
Cool, now it's actually creating another xD ticket

**Comment by OmerBenGera** [comment] 2022-06-23 16:32
Fixed in latest dev build

**Comment by xOpasik** [comment] 2022-06-23 17:33
Unfortunately, after updating the plugin, rebooting and a new island, it still goes back to the level
![image](https://user-images.githubusercontent.com/105610066/175359980-b6022f2a-35c1-4b94-9767-eebed596d08b.png)

**Comment by xOpasik** [comment] 2022-06-24 09:55
I have just such a placehold, maybe I have to set up a different one, but I don't know
%superior_island_level%

**Comment by OmerBenGera** [comment] 2022-06-24 10:10
> I have just such a placehold, maybe I have to set up a different one, but I don't know %superior_island_level%

that's the level of your island, not sure what you're saying here.

**Comment by xOpasik** [comment] 2022-06-24 10:19
The point is that despite upgrading superiorblock2 and the oneblock module, even making a completely new island. It is while extracting blocks from the generator that oneblock still takes points

**Comment by xOpasik** [comment] 2022-06-24 10:21
![image](https://user-images.githubusercontent.com/105610066/175515813-8c703c60-b243-4fc1-a713-1a2cb3feb739.png)
![image](https://user-images.githubusercontent.com/105610066/175515942-9e09b789-eb93-4048-a9b3-82d2bd43080a.png)

**Comment by xOpasik** [comment] 2022-06-26 09:35
umm?

**Comment by xOpasik** [comment] 2022-06-26 19:16
I have uploaded the latest versions and unfortunately still the same

**Comment by OmerBenGera** [comment] 2022-06-26 20:08
> I have uploaded the latest versions and unfortunately still the same

I will look into it again in the weekend, be patient.

**Comment by xOpasik** [comment] 2022-06-27 06:51
Okay, I'm just typing because you closed your ticket

**Comment by OmerBenGera** [comment] 2022-07-02 10:01
Fixed in latest dev build, sorry about that

**Closed by OmerBenGera** 2022-07-02 10:01 UTC
Labels: ✔️ Confirmed

**Comment by xOpasik** [comment] 2022-07-02 12:54
I checked, even with clay he subtracts level points.

In general, you can see a huge difference with this, but still some blocks take the level back permanently

**Comment by OmerBenGera** [comment] 2022-07-02 15:55
> I checked, even with clay he subtracts level points.
> 
> In general, you can see a huge difference with this, but still some blocks take the level back permanently

When the block is generated, your level increases; when you break the block, the level will be decreased - therefore, levels will not go down permanently as they did before.
If they go down but before they went up, it's totally fine and this is an intended behavior. Use `/is level` to recalculate your level, and you will see that the levels don't go down anymore as they used to.

**Comment by xOpasik** [comment] 2022-07-02 20:19
Okey, thanks
