### ISSUE TITLE
Random blocks & entities spawning after oneblock is broken for the first two times

### ISSUE THREAD

**Issue by AMZAKU** [BG-Software-LLC/SSB-OneBlock#73] opened 2023-11-17 15:59 UTC
### Minecraft's Version

Minecraft version: 1.20.2 

This server is running Pufferfish version git-Pufferfish-29 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 0ba7617 on HEAD)

### Plugin's Version

SuperiorSkyblock: 2023.3
Oneblock: Latest 2023.3

### Describe the bug

When breaking the first two blocks of a phase it will start spawning randoms blocks from that phase until it reaches cooldown. It'll still happen after the cooldown runs out. 

### To Reproduce

Create a new fresh oneblock island, break the first two blocks, then random blocks and entities will start spawning until you reach the cooldown block limit.

### Additional Information

Module configuration is by default, I only added a whitelisted schematic.

Here is a clip that might help reproducing the bug: https://medal.tv/games/minecraft/clips/1EfVFNkAvzhPlQ/d1337IeookFn?invite=cr-MSxaZkcsNjQxNDcwMTIs

**Comment by Baterka** [comment] 2023-11-17 18:31
Same issue hapenning to me

**Comment by AMZAKU** [comment] 2023-11-20 16:32
Reverting 8306a76 seems to fix it

**Comment by Kocimietka7192** [comment] 2023-12-03 17:21
> Reverting [8306a76](https://github.com/BG-Software-LLC/SSB-OneBlock/commit/8306a76087635ab008d09a552fa813254dbb9838) seems to fix it

no, it hasn't been fixed, after all, we wrote that the error occurs on the given versions. so I don't understand why you are announcing that it probably has been fixed....

**Comment by CodeAsm** [comment] 2023-12-03 20:36
reverting means that commit broke it, if one where to revert those changes, it might fix current builds. Or thats what I think AMZAKU means, im testing it (learned alott in the past few hours). I can now build the current version from source, ill try undoing those changes to see if that was the cause.

**Comment by OmerBenGera** [comment] 2023-12-15 16:03
Duplicate of #71

**Closed by OmerBenGera** 2023-12-15 16:03 UTC
Labels: Pending
